/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Shortened version of existing reconstruction reference
    /// </summary>
    [DataContract(Name = "VT.ApiPlaneraResa.Web.V4.Models.Journeys.ShortenedReconstructionRefApiModel")]
    public partial class VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel : IEquatable<VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel" /> class.
        /// </summary>
        /// <param name="shortenedReconstructionRef">shortenedReconstructionRef.</param>
        public VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel(string shortenedReconstructionRef = default(string))
        {
            this.ShortenedReconstructionRef = shortenedReconstructionRef;
        }

        /// <summary>
        /// Gets or Sets ShortenedReconstructionRef
        /// </summary>
        [DataMember(Name = "shortenedReconstructionRef", EmitDefaultValue = true)]
        public string ShortenedReconstructionRef { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel {\n");
            sb.Append("  ShortenedReconstructionRef: ").Append(ShortenedReconstructionRef).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel);
        }

        /// <summary>
        /// Returns true if VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel instances are equal
        /// </summary>
        /// <param name="input">Instance of VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VTApiPlaneraResaWebV4ModelsJourneysShortenedReconstructionRefApiModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ShortenedReconstructionRef == input.ShortenedReconstructionRef ||
                    (this.ShortenedReconstructionRef != null &&
                    this.ShortenedReconstructionRef.Equals(input.ShortenedReconstructionRef))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ShortenedReconstructionRef != null)
                {
                    hashCode = (hashCode * 59) + this.ShortenedReconstructionRef.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
