/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Information about a location.
    /// </summary>
    [DataContract(Name = "VT.ApiPlaneraResa.Web.V4.Models.Locations.LocationApiModel")]
    public partial class VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel : IEquatable<VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets LocationType
        /// </summary>
        [DataMember(Name = "locationType", IsRequired = true, EmitDefaultValue = true)]
        public VTApiPlaneraResaWebV4ModelsLocationType LocationType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel" /> class.
        /// </summary>
        /// <param name="gid">The 16-digit Västtrafik gid..</param>
        /// <param name="name">The location name. (required).</param>
        /// <param name="locationType">locationType (required).</param>
        /// <param name="latitude">The WGS84 latitude of the location..</param>
        /// <param name="longitude">The WGS84 longitude of the location..</param>
        /// <param name="platform">The location platform, only available for stop points..</param>
        /// <param name="straightLineDistanceInMeters">The location straight line distance in meters..</param>
        /// <param name="hasLocalService">Is \&quot;Närtrafik\&quot; (Local Service) available for the location?  Values are only available for LocationType: StopArea, PointOfInterest and Address.  Values are only available for endpoint: locations/by-text..</param>
        public VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel(string gid = default(string), string name = default(string), VTApiPlaneraResaWebV4ModelsLocationType locationType = default(VTApiPlaneraResaWebV4ModelsLocationType), double? latitude = default(double?), double? longitude = default(double?), string platform = default(string), int? straightLineDistanceInMeters = default(int?), bool? hasLocalService = default(bool?))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel and cannot be null");
            }
            this.Name = name;
            this.LocationType = locationType;
            this.Gid = gid;
            this.Latitude = latitude;
            this.Longitude = longitude;
            this.Platform = platform;
            this.StraightLineDistanceInMeters = straightLineDistanceInMeters;
            this.HasLocalService = hasLocalService;
        }

        /// <summary>
        /// The 16-digit Västtrafik gid.
        /// </summary>
        /// <value>The 16-digit Västtrafik gid.</value>
        [DataMember(Name = "gid", EmitDefaultValue = true)]
        public string Gid { get; set; }

        /// <summary>
        /// The location name.
        /// </summary>
        /// <value>The location name.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The WGS84 latitude of the location.
        /// </summary>
        /// <value>The WGS84 latitude of the location.</value>
        [DataMember(Name = "latitude", EmitDefaultValue = true)]
        public double? Latitude { get; set; }

        /// <summary>
        /// The WGS84 longitude of the location.
        /// </summary>
        /// <value>The WGS84 longitude of the location.</value>
        [DataMember(Name = "longitude", EmitDefaultValue = true)]
        public double? Longitude { get; set; }

        /// <summary>
        /// The location platform, only available for stop points.
        /// </summary>
        /// <value>The location platform, only available for stop points.</value>
        [DataMember(Name = "platform", EmitDefaultValue = true)]
        public string Platform { get; set; }

        /// <summary>
        /// The location straight line distance in meters.
        /// </summary>
        /// <value>The location straight line distance in meters.</value>
        [DataMember(Name = "straightLineDistanceInMeters", EmitDefaultValue = true)]
        public int? StraightLineDistanceInMeters { get; set; }

        /// <summary>
        /// Is \&quot;Närtrafik\&quot; (Local Service) available for the location?  Values are only available for LocationType: StopArea, PointOfInterest and Address.  Values are only available for endpoint: locations/by-text.
        /// </summary>
        /// <value>Is \&quot;Närtrafik\&quot; (Local Service) available for the location?  Values are only available for LocationType: StopArea, PointOfInterest and Address.  Values are only available for endpoint: locations/by-text.</value>
        [DataMember(Name = "hasLocalService", EmitDefaultValue = true)]
        public bool? HasLocalService { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  LocationType: ").Append(LocationType).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  StraightLineDistanceInMeters: ").Append(StraightLineDistanceInMeters).Append("\n");
            sb.Append("  HasLocalService: ").Append(HasLocalService).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel);
        }

        /// <summary>
        /// Returns true if VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel instances are equal
        /// </summary>
        /// <param name="input">Instance of VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VTApiPlaneraResaWebV4ModelsLocationsLocationApiModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Gid == input.Gid ||
                    (this.Gid != null &&
                    this.Gid.Equals(input.Gid))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.LocationType == input.LocationType ||
                    this.LocationType.Equals(input.LocationType)
                ) && 
                (
                    this.Latitude == input.Latitude ||
                    (this.Latitude != null &&
                    this.Latitude.Equals(input.Latitude))
                ) && 
                (
                    this.Longitude == input.Longitude ||
                    (this.Longitude != null &&
                    this.Longitude.Equals(input.Longitude))
                ) && 
                (
                    this.Platform == input.Platform ||
                    (this.Platform != null &&
                    this.Platform.Equals(input.Platform))
                ) && 
                (
                    this.StraightLineDistanceInMeters == input.StraightLineDistanceInMeters ||
                    (this.StraightLineDistanceInMeters != null &&
                    this.StraightLineDistanceInMeters.Equals(input.StraightLineDistanceInMeters))
                ) && 
                (
                    this.HasLocalService == input.HasLocalService ||
                    (this.HasLocalService != null &&
                    this.HasLocalService.Equals(input.HasLocalService))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Gid != null)
                {
                    hashCode = (hashCode * 59) + this.Gid.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.LocationType.GetHashCode();
                if (this.Latitude != null)
                {
                    hashCode = (hashCode * 59) + this.Latitude.GetHashCode();
                }
                if (this.Longitude != null)
                {
                    hashCode = (hashCode * 59) + this.Longitude.GetHashCode();
                }
                if (this.Platform != null)
                {
                    hashCode = (hashCode * 59) + this.Platform.GetHashCode();
                }
                if (this.StraightLineDistanceInMeters != null)
                {
                    hashCode = (hashCode * 59) + this.StraightLineDistanceInMeters.GetHashCode();
                }
                if (this.HasLocalService != null)
                {
                    hashCode = (hashCode * 59) + this.HasLocalService.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            yield break;
        }
    }

}
