/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel
    /// </summary>
    [DataContract(Name = "VT.ApiPlaneraResa.Web.V4.Models.Products.TicketSpecificationApiModel")]
    public partial class VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel : IEquatable<VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets ProductType
        /// </summary>
        [DataMember(Name = "productType", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsProductTypeEnum? ProductType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel" /> class.
        /// </summary>
        /// <param name="ticketName">ticketName.</param>
        /// <param name="configurations">configurations.</param>
        /// <param name="productType">productType.</param>
        public VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel(string ticketName = default(string), List<VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel> configurations = default(List<VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel>), VTApiPlaneraResaWebV4ModelsProductTypeEnum? productType = default(VTApiPlaneraResaWebV4ModelsProductTypeEnum?))
        {
            this.TicketName = ticketName;
            this.Configurations = configurations;
            this.ProductType = productType;
        }

        /// <summary>
        /// Gets or Sets TicketName
        /// </summary>
        [DataMember(Name = "ticketName", EmitDefaultValue = true)]
        public string TicketName { get; set; }

        /// <summary>
        /// Gets or Sets Configurations
        /// </summary>
        [DataMember(Name = "configurations", EmitDefaultValue = true)]
        public List<VTApiPlaneraResaWebV4ModelsProductsTicketConfigurationApiModel> Configurations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel {\n");
            sb.Append("  TicketName: ").Append(TicketName).Append("\n");
            sb.Append("  Configurations: ").Append(Configurations).Append("\n");
            sb.Append("  ProductType: ").Append(ProductType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel);
        }

        /// <summary>
        /// Returns true if VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel instances are equal
        /// </summary>
        /// <param name="input">Instance of VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VTApiPlaneraResaWebV4ModelsProductsTicketSpecificationApiModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TicketName == input.TicketName ||
                    (this.TicketName != null &&
                    this.TicketName.Equals(input.TicketName))
                ) && 
                (
                    this.Configurations == input.Configurations ||
                    this.Configurations != null &&
                    input.Configurations != null &&
                    this.Configurations.SequenceEqual(input.Configurations)
                ) && 
                (
                    this.ProductType == input.ProductType ||
                    this.ProductType.Equals(input.ProductType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TicketName != null)
                {
                    hashCode = (hashCode * 59) + this.TicketName.GetHashCode();
                }
                if (this.Configurations != null)
                {
                    hashCode = (hashCode * 59) + this.Configurations.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ProductType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
