/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines VT.ApiPlaneraResa.Core.Models.PositionTransportMode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaCoreModelsPositionTransportMode
    {
        /// <summary>
        /// Enum Tram for value: tram
        /// </summary>
        [EnumMember(Value = "tram")]
        Tram = 1,

        /// <summary>
        /// Enum Bus for value: bus
        /// </summary>
        [EnumMember(Value = "bus")]
        Bus = 2,

        /// <summary>
        /// Enum Ferry for value: ferry
        /// </summary>
        [EnumMember(Value = "ferry")]
        Ferry = 3,

        /// <summary>
        /// Enum Train for value: train
        /// </summary>
        [EnumMember(Value = "train")]
        Train = 4,

        /// <summary>
        /// Enum Taxi for value: taxi
        /// </summary>
        [EnumMember(Value = "taxi")]
        Taxi = 5
    }

}
