/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Specifies an orientation of a link segment.
    /// </summary>
    /// <value>Specifies an orientation of a link segment.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsLinkSegmentOrientation
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown,

        /// <summary>
        /// Enum North for value: north
        /// </summary>
        [EnumMember(Value = "north")]
        North,

        /// <summary>
        /// Enum South for value: south
        /// </summary>
        [EnumMember(Value = "south")]
        South,

        /// <summary>
        /// Enum East for value: east
        /// </summary>
        [EnumMember(Value = "east")]
        East,

        /// <summary>
        /// Enum West for value: west
        /// </summary>
        [EnumMember(Value = "west")]
        West,

        /// <summary>
        /// Enum Northeast for value: northeast
        /// </summary>
        [EnumMember(Value = "northeast")]
        Northeast,

        /// <summary>
        /// Enum Southeast for value: southeast
        /// </summary>
        [EnumMember(Value = "southeast")]
        Southeast,

        /// <summary>
        /// Enum Northwest for value: northwest
        /// </summary>
        [EnumMember(Value = "northwest")]
        Northwest,

        /// <summary>
        /// Enum Southwest for value: southwest
        /// </summary>
        [EnumMember(Value = "southwest")]
        Southwest
    }

}
