/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The different kinds of detailed information that could be included in a get journey details request.
    /// </summary>
    /// <value>The different kinds of detailed information that could be included in a get journey details request.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsJourneyDetailsIncludeType
    {
        /// <summary>
        /// Enum Ticketsuggestions for value: ticketsuggestions
        /// </summary>
        [EnumMember(Value = "ticketsuggestions")]
        Ticketsuggestions = 1,

        /// <summary>
        /// Enum Triplegcoordinates for value: triplegcoordinates
        /// </summary>
        [EnumMember(Value = "triplegcoordinates")]
        Triplegcoordinates = 2,

        /// <summary>
        /// Enum Validzones for value: validzones
        /// </summary>
        [EnumMember(Value = "validzones")]
        Validzones = 3,

        /// <summary>
        /// Enum Servicejourneycalls for value: servicejourneycalls
        /// </summary>
        [EnumMember(Value = "servicejourneycalls")]
        Servicejourneycalls = 4,

        /// <summary>
        /// Enum Servicejourneycoordinates for value: servicejourneycoordinates
        /// </summary>
        [EnumMember(Value = "servicejourneycoordinates")]
        Servicejourneycoordinates = 5,

        /// <summary>
        /// Enum Links for value: links
        /// </summary>
        [EnumMember(Value = "links")]
        Links = 6,

        /// <summary>
        /// Enum Occupancy for value: occupancy
        /// </summary>
        [EnumMember(Value = "occupancy")]
        Occupancy = 7
    }

}
