/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// The type of area for a set of zones.
    /// </summary>
    /// <value>The type of area for a set of zones.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsAreaType
    {
        /// <summary>
        /// Enum None for value: none
        /// </summary>
        [EnumMember(Value = "none")]
        None = 1,

        /// <summary>
        /// Enum Standard for value: standard
        /// </summary>
        [EnumMember(Value = "standard")]
        Standard = 2,

        /// <summary>
        /// Enum Mini for value: mini
        /// </summary>
        [EnumMember(Value = "mini")]
        Mini = 3,

        /// <summary>
        /// Enum Extra for value: extra
        /// </summary>
        [EnumMember(Value = "extra")]
        Extra = 4,

        /// <summary>
        /// Enum Leisure for value: leisure
        /// </summary>
        [EnumMember(Value = "leisure")]
        Leisure = 5
    }

}
