/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents the source from which the occupancy information originate.
    /// </summary>
    /// <value>Represents the source from which the occupancy information originate.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsOccupancyInformationSource
    {
        /// <summary>
        /// Enum Prediction for value: prediction
        /// </summary>
        [EnumMember(Value = "prediction")]
        Prediction = 1,

        /// <summary>
        /// Enum Realtime for value: realtime
        /// </summary>
        [EnumMember(Value = "realtime")]
        Realtime = 2
    }

}
