/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Different types of time validity.
    /// </summary>
    /// <value>Different types of time validity.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsTimeValidityType
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown,

        /// <summary>
        /// Enum Amountunit for value: amountunit
        /// </summary>
        [EnumMember(Value = "amountunit")]
        Amountunit,

        /// <summary>
        /// Enum Fromtodate for value: fromtodate
        /// </summary>
        [EnumMember(Value = "fromtodate")]
        Fromtodate,

        /// <summary>
        /// Enum Fromtodatetime for value: fromtodatetime
        /// </summary>
        [EnumMember(Value = "fromtodatetime")]
        Fromtodatetime
    }

}
