/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents the different types of location.
    /// </summary>
    /// <value>Represents the different types of location.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsLocationType
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown,

        /// <summary>
        /// Enum Stoparea for value: stoparea
        /// </summary>
        [EnumMember(Value = "stoparea")]
        Stoparea,

        /// <summary>
        /// Enum Stoppoint for value: stoppoint
        /// </summary>
        [EnumMember(Value = "stoppoint")]
        Stoppoint,

        /// <summary>
        /// Enum Address for value: address
        /// </summary>
        [EnumMember(Value = "address")]
        Address,

        /// <summary>
        /// Enum Pointofinterest for value: pointofinterest
        /// </summary>
        [EnumMember(Value = "pointofinterest")]
        Pointofinterest,

        /// <summary>
        /// Enum Metastation for value: metastation
        /// </summary>
        [EnumMember(Value = "metastation")]
        Metastation
    }

}
