/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents the different types of sub transport modes, only applicable when using transport mode &#39;Train&#39;.
    /// </summary>
    /// <value>Represents the different types of sub transport modes, only applicable when using transport mode &#39;Train&#39;.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsTransportSubMode
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown,

        /// <summary>
        /// Enum None for value: none
        /// </summary>
        [EnumMember(Value = "none")]
        None,

        /// <summary>
        /// Enum Vasttagen for value: vasttagen
        /// </summary>
        [EnumMember(Value = "vasttagen")]
        Vasttagen,

        /// <summary>
        /// Enum Longdistancetrain for value: longdistancetrain
        /// </summary>
        [EnumMember(Value = "longdistancetrain")]
        Longdistancetrain,

        /// <summary>
        /// Enum Regionaltrain for value: regionaltrain
        /// </summary>
        [EnumMember(Value = "regionaltrain")]
        Regionaltrain
    }

}
