/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Information specifying the interval when valid journey information is available, i.e. when it is possible to search journeys.
    /// </summary>
    [DataContract(Name = "VT.ApiPlaneraResa.Web.V4.Models.ValidTimeIntervalApiModel")]
    public partial class VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel : IEquatable<VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel" /> class.
        /// </summary>
        /// <param name="validFrom">The start time of the interval when valid journey information is available, specified in RFC 3339 format..</param>
        /// <param name="validUntil">The end time of the interval when valid journey information is available, specified in RFC 3339 format..</param>
        public VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel(string validFrom = default(string), string validUntil = default(string))
        {
            this.ValidFrom = validFrom;
            this.ValidUntil = validUntil;
        }

        /// <summary>
        /// The start time of the interval when valid journey information is available, specified in RFC 3339 format.
        /// </summary>
        /// <value>The start time of the interval when valid journey information is available, specified in RFC 3339 format.</value>
        [DataMember(Name = "validFrom", EmitDefaultValue = true)]
        public string ValidFrom { get; set; }

        /// <summary>
        /// The end time of the interval when valid journey information is available, specified in RFC 3339 format.
        /// </summary>
        /// <value>The end time of the interval when valid journey information is available, specified in RFC 3339 format.</value>
        [DataMember(Name = "validUntil", EmitDefaultValue = true)]
        public string ValidUntil { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel {\n");
            sb.Append("  ValidFrom: ").Append(ValidFrom).Append("\n");
            sb.Append("  ValidUntil: ").Append(ValidUntil).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel);
        }

        /// <summary>
        /// Returns true if VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel instances are equal
        /// </summary>
        /// <param name="input">Instance of VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VTApiPlaneraResaWebV4ModelsValidTimeIntervalApiModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ValidFrom == input.ValidFrom ||
                    (this.ValidFrom != null &&
                    this.ValidFrom.Equals(input.ValidFrom))
                ) && 
                (
                    this.ValidUntil == input.ValidUntil ||
                    (this.ValidUntil != null &&
                    this.ValidUntil.Equals(input.ValidUntil))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ValidFrom != null)
                {
                    hashCode = (hashCode * 59) + this.ValidFrom.GetHashCode();
                }
                if (this.ValidUntil != null)
                {
                    hashCode = (hashCode * 59) + this.ValidUntil.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
