/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A subset of LocationType
    /// </summary>
    /// <value>A subset of LocationType</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsLocationByTextType
    {
        /// <summary>
        /// Enum Stoparea for value: stoparea
        /// </summary>
        [EnumMember(Value = "stoparea")]
        Stoparea = 1,

        /// <summary>
        /// Enum Address for value: address
        /// </summary>
        [EnumMember(Value = "address")]
        Address = 2,

        /// <summary>
        /// Enum Pointofinterest for value: pointofinterest
        /// </summary>
        [EnumMember(Value = "pointofinterest")]
        Pointofinterest = 3,

        /// <summary>
        /// Enum Metastation for value: metastation
        /// </summary>
        [EnumMember(Value = "metastation")]
        Metastation = 4
    }

}
