/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// A subset of LocationType
    /// </summary>
    /// <value>A subset of LocationType</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsLocationByCoordinatesType
    {
        /// <summary>
        /// Enum Stoparea for value: stoparea
        /// </summary>
        [EnumMember(Value = "stoparea")]
        Stoparea = 1,

        /// <summary>
        /// Enum Stoppoint for value: stoppoint
        /// </summary>
        [EnumMember(Value = "stoppoint")]
        Stoppoint = 2,

        /// <summary>
        /// Enum Pointofinterest for value: pointofinterest
        /// </summary>
        [EnumMember(Value = "pointofinterest")]
        Pointofinterest = 3,

        /// <summary>
        /// Enum Metastation for value: metastation
        /// </summary>
        [EnumMember(Value = "metastation")]
        Metastation = 4
    }

}
