/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Unit of duration of validity of a single punch.
    /// </summary>
    /// <value>Unit of duration of validity of a single punch.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsPunchConfigurationDurationUnitApiModel
    {
        /// <summary>
        /// Enum Hours for value: hours
        /// </summary>
        [EnumMember(Value = "hours")]
        Hours = 1
    }

}
