/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents time limitations for a ticket.
    /// </summary>
    /// <value>Represents time limitations for a ticket.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsTimeLimitation
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown,

        /// <summary>
        /// Enum Heltid for value: heltid
        /// </summary>
        [EnumMember(Value = "heltid")]
        Heltid,

        /// <summary>
        /// Enum Lagtrafik for value: lagtrafik
        /// </summary>
        [EnumMember(Value = "lagtrafik")]
        Lagtrafik,

        /// <summary>
        /// Enum Skolkort04till19 for value: skolkort04till19
        /// </summary>
        [EnumMember(Value = "skolkort04till19")]
        Skolkort04till19,

        /// <summary>
        /// Enum Skolkort04till22 for value: skolkort04till22
        /// </summary>
        [EnumMember(Value = "skolkort04till22")]
        Skolkort04till22,

        /// <summary>
        /// Enum Skolkort04till1930 for value: skolkort04till1930
        /// </summary>
        [EnumMember(Value = "skolkort04till1930")]
        Skolkort04till1930,

        /// <summary>
        /// Enum Fritid100 for value: fritid100
        /// </summary>
        [EnumMember(Value = "fritid100")]
        Fritid100,

        /// <summary>
        /// Enum Fritidkomplement for value: fritidkomplement
        /// </summary>
        [EnumMember(Value = "fritidkomplement")]
        Fritidkomplement,

        /// <summary>
        /// Enum Fritidvardag19till22 for value: fritidvardag19till22
        /// </summary>
        [EnumMember(Value = "fritidvardag19till22")]
        Fritidvardag19till22,

        /// <summary>
        /// Enum Fritidvardag14till24 for value: fritidvardag14till24
        /// </summary>
        [EnumMember(Value = "fritidvardag14till24")]
        Fritidvardag14till24,

        /// <summary>
        /// Enum Fritidkvallhelg for value: fritidkvallhelg
        /// </summary>
        [EnumMember(Value = "fritidkvallhelg")]
        Fritidkvallhelg,

        /// <summary>
        /// Enum Fritidkvallhelglov for value: fritidkvallhelglov
        /// </summary>
        [EnumMember(Value = "fritidkvallhelglov")]
        Fritidkvallhelglov,

        /// <summary>
        /// Enum Fritidjulsommarlov for value: fritidjulsommarlov
        /// </summary>
        [EnumMember(Value = "fritidjulsommarlov")]
        Fritidjulsommarlov,

        /// <summary>
        /// Enum Fritidale for value: fritidale
        /// </summary>
        [EnumMember(Value = "fritidale")]
        Fritidale
    }

}
