/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Information about a service journey.
    /// </summary>
    [DataContract(Name = "VT.ApiPlaneraResa.Web.V4.Models.JourneyDetails.ServiceJourneyApiModel")]
    public partial class VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel : IEquatable<VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel" /> class.
        /// </summary>
        /// <param name="gid">16-digit Västtrafik service journey gid that the trip leg is a part of..</param>
        /// <param name="direction">A description of the direction..</param>
        /// <param name="directionDetails">directionDetails.</param>
        /// <param name="line">line.</param>
        /// <param name="serviceJourneyCoordinates">The coordinates on the service journey..</param>
        /// <param name="callsOnServiceJourney">All calls on the service journey..</param>
        public VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel(string gid = default(string), string direction = default(string), VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel directionDetails = default(VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel), VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModel line = default(VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModel), List<VTApiPlaneraResaWebV4ModelsCoordinateApiModel> serviceJourneyCoordinates = default(List<VTApiPlaneraResaWebV4ModelsCoordinateApiModel>), List<VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel> callsOnServiceJourney = default(List<VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel>))
        {
            this.Gid = gid;
            this.Direction = direction;
            this.DirectionDetails = directionDetails;
            this.Line = line;
            this.ServiceJourneyCoordinates = serviceJourneyCoordinates;
            this.CallsOnServiceJourney = callsOnServiceJourney;
        }

        /// <summary>
        /// 16-digit Västtrafik service journey gid that the trip leg is a part of.
        /// </summary>
        /// <value>16-digit Västtrafik service journey gid that the trip leg is a part of.</value>
        [DataMember(Name = "gid", EmitDefaultValue = true)]
        public string Gid { get; set; }

        /// <summary>
        /// A description of the direction.
        /// </summary>
        /// <value>A description of the direction.</value>
        [DataMember(Name = "direction", EmitDefaultValue = true)]
        public string Direction { get; set; }

        /// <summary>
        /// Gets or Sets DirectionDetails
        /// </summary>
        [DataMember(Name = "directionDetails", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel DirectionDetails { get; set; }

        /// <summary>
        /// Gets or Sets Line
        /// </summary>
        [DataMember(Name = "line", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsJourneyDetailsLineDetailsApiModel Line { get; set; }

        /// <summary>
        /// The coordinates on the service journey.
        /// </summary>
        /// <value>The coordinates on the service journey.</value>
        [DataMember(Name = "serviceJourneyCoordinates", EmitDefaultValue = true)]
        public List<VTApiPlaneraResaWebV4ModelsCoordinateApiModel> ServiceJourneyCoordinates { get; set; }

        /// <summary>
        /// All calls on the service journey.
        /// </summary>
        /// <value>All calls on the service journey.</value>
        [DataMember(Name = "callsOnServiceJourney", EmitDefaultValue = true)]
        public List<VTApiPlaneraResaWebV4ModelsJourneyDetailsCallDetailsApiModel> CallsOnServiceJourney { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  Direction: ").Append(Direction).Append("\n");
            sb.Append("  DirectionDetails: ").Append(DirectionDetails).Append("\n");
            sb.Append("  Line: ").Append(Line).Append("\n");
            sb.Append("  ServiceJourneyCoordinates: ").Append(ServiceJourneyCoordinates).Append("\n");
            sb.Append("  CallsOnServiceJourney: ").Append(CallsOnServiceJourney).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel);
        }

        /// <summary>
        /// Returns true if VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel instances are equal
        /// </summary>
        /// <param name="input">Instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VTApiPlaneraResaWebV4ModelsJourneyDetailsServiceJourneyApiModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Gid == input.Gid ||
                    (this.Gid != null &&
                    this.Gid.Equals(input.Gid))
                ) && 
                (
                    this.Direction == input.Direction ||
                    (this.Direction != null &&
                    this.Direction.Equals(input.Direction))
                ) && 
                (
                    this.DirectionDetails == input.DirectionDetails ||
                    (this.DirectionDetails != null &&
                    this.DirectionDetails.Equals(input.DirectionDetails))
                ) && 
                (
                    this.Line == input.Line ||
                    (this.Line != null &&
                    this.Line.Equals(input.Line))
                ) && 
                (
                    this.ServiceJourneyCoordinates == input.ServiceJourneyCoordinates ||
                    this.ServiceJourneyCoordinates != null &&
                    input.ServiceJourneyCoordinates != null &&
                    this.ServiceJourneyCoordinates.SequenceEqual(input.ServiceJourneyCoordinates)
                ) && 
                (
                    this.CallsOnServiceJourney == input.CallsOnServiceJourney ||
                    this.CallsOnServiceJourney != null &&
                    input.CallsOnServiceJourney != null &&
                    this.CallsOnServiceJourney.SequenceEqual(input.CallsOnServiceJourney)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Gid != null)
                {
                    hashCode = (hashCode * 59) + this.Gid.GetHashCode();
                }
                if (this.Direction != null)
                {
                    hashCode = (hashCode * 59) + this.Direction.GetHashCode();
                }
                if (this.DirectionDetails != null)
                {
                    hashCode = (hashCode * 59) + this.DirectionDetails.GetHashCode();
                }
                if (this.Line != null)
                {
                    hashCode = (hashCode * 59) + this.Line.GetHashCode();
                }
                if (this.ServiceJourneyCoordinates != null)
                {
                    hashCode = (hashCode * 59) + this.ServiceJourneyCoordinates.GetHashCode();
                }
                if (this.CallsOnServiceJourney != null)
                {
                    hashCode = (hashCode * 59) + this.CallsOnServiceJourney.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
