/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Different types of traveller category.
    /// </summary>
    /// <value>Different types of traveller category.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsTravellerCategory
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown,

        /// <summary>
        /// Enum Adult for value: adult
        /// </summary>
        [EnumMember(Value = "adult")]
        Adult,

        /// <summary>
        /// Enum Youth for value: youth
        /// </summary>
        [EnumMember(Value = "youth")]
        Youth
    }

}
