/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Detailed information about a journey.
    /// </summary>
    [DataContract(Name = "VT.ApiPlaneraResa.Web.V4.Models.JourneyDetails.JourneyDetailsApiModel")]
    public partial class VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel : IEquatable<VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel" /> class.
        /// </summary>
        /// <param name="departureAccessLink">departureAccessLink.</param>
        /// <param name="tripLegs">Detailed information, including stops, about the trip legs..</param>
        /// <param name="connectionLinks">A list of ConnectionLinks between TripLegs, when applicable. The internal order of TripLegs and ConnectionLinks is defined by Index-property on the objects..</param>
        /// <param name="arrivalAccessLink">arrivalAccessLink.</param>
        /// <param name="destinationLink">destinationLink.</param>
        /// <param name="ticketSuggestionsResult">ticketSuggestionsResult.</param>
        /// <param name="tariffZones">The tariff zones that the journey traverses..</param>
        /// <param name="occupancy">occupancy.</param>
        public VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel(VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModel departureAccessLink = default(VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModel), List<VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel> tripLegs = default(List<VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel>), List<VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModel> connectionLinks = default(List<VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModel>), VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModel arrivalAccessLink = default(VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModel), VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModel destinationLink = default(VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModel), VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModel ticketSuggestionsResult = default(VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModel), List<VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel> tariffZones = default(List<VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel>), VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel occupancy = default(VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel))
        {
            this.DepartureAccessLink = departureAccessLink;
            this.TripLegs = tripLegs;
            this.ConnectionLinks = connectionLinks;
            this.ArrivalAccessLink = arrivalAccessLink;
            this.DestinationLink = destinationLink;
            this.TicketSuggestionsResult = ticketSuggestionsResult;
            this.TariffZones = tariffZones;
            this.Occupancy = occupancy;
        }

        /// <summary>
        /// Gets or Sets DepartureAccessLink
        /// </summary>
        [DataMember(Name = "departureAccessLink", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsJourneyDetailsDepartureAccessLinkApiModel DepartureAccessLink { get; set; }

        /// <summary>
        /// Detailed information, including stops, about the trip legs.
        /// </summary>
        /// <value>Detailed information, including stops, about the trip legs.</value>
        [DataMember(Name = "tripLegs", EmitDefaultValue = true)]
        public List<VTApiPlaneraResaWebV4ModelsJourneyDetailsTripLegDetailsApiModel> TripLegs { get; set; }

        /// <summary>
        /// A list of ConnectionLinks between TripLegs, when applicable. The internal order of TripLegs and ConnectionLinks is defined by Index-property on the objects.
        /// </summary>
        /// <value>A list of ConnectionLinks between TripLegs, when applicable. The internal order of TripLegs and ConnectionLinks is defined by Index-property on the objects.</value>
        [DataMember(Name = "connectionLinks", EmitDefaultValue = true)]
        public List<VTApiPlaneraResaWebV4ModelsJourneyDetailsConnectionLinkApiModel> ConnectionLinks { get; set; }

        /// <summary>
        /// Gets or Sets ArrivalAccessLink
        /// </summary>
        [DataMember(Name = "arrivalAccessLink", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsJourneyDetailsArrivalAccessLinkApiModel ArrivalAccessLink { get; set; }

        /// <summary>
        /// Gets or Sets DestinationLink
        /// </summary>
        [DataMember(Name = "destinationLink", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsJourneyDetailsDestinationLinkApiModel DestinationLink { get; set; }

        /// <summary>
        /// Gets or Sets TicketSuggestionsResult
        /// </summary>
        [DataMember(Name = "ticketSuggestionsResult", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsJourneyDetailsTicketSuggestionsResultApiModel TicketSuggestionsResult { get; set; }

        /// <summary>
        /// The tariff zones that the journey traverses.
        /// </summary>
        /// <value>The tariff zones that the journey traverses.</value>
        [DataMember(Name = "tariffZones", EmitDefaultValue = true)]
        public List<VTApiPlaneraResaWebV4ModelsJourneyDetailsTariffZoneApiModel> TariffZones { get; set; }

        /// <summary>
        /// Gets or Sets Occupancy
        /// </summary>
        [DataMember(Name = "occupancy", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsOccupancyInformationApiModel Occupancy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel {\n");
            sb.Append("  DepartureAccessLink: ").Append(DepartureAccessLink).Append("\n");
            sb.Append("  TripLegs: ").Append(TripLegs).Append("\n");
            sb.Append("  ConnectionLinks: ").Append(ConnectionLinks).Append("\n");
            sb.Append("  ArrivalAccessLink: ").Append(ArrivalAccessLink).Append("\n");
            sb.Append("  DestinationLink: ").Append(DestinationLink).Append("\n");
            sb.Append("  TicketSuggestionsResult: ").Append(TicketSuggestionsResult).Append("\n");
            sb.Append("  TariffZones: ").Append(TariffZones).Append("\n");
            sb.Append("  Occupancy: ").Append(Occupancy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel);
        }

        /// <summary>
        /// Returns true if VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel instances are equal
        /// </summary>
        /// <param name="input">Instance of VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VTApiPlaneraResaWebV4ModelsJourneyDetailsJourneyDetailsApiModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DepartureAccessLink == input.DepartureAccessLink ||
                    (this.DepartureAccessLink != null &&
                    this.DepartureAccessLink.Equals(input.DepartureAccessLink))
                ) && 
                (
                    this.TripLegs == input.TripLegs ||
                    this.TripLegs != null &&
                    input.TripLegs != null &&
                    this.TripLegs.SequenceEqual(input.TripLegs)
                ) && 
                (
                    this.ConnectionLinks == input.ConnectionLinks ||
                    this.ConnectionLinks != null &&
                    input.ConnectionLinks != null &&
                    this.ConnectionLinks.SequenceEqual(input.ConnectionLinks)
                ) && 
                (
                    this.ArrivalAccessLink == input.ArrivalAccessLink ||
                    (this.ArrivalAccessLink != null &&
                    this.ArrivalAccessLink.Equals(input.ArrivalAccessLink))
                ) && 
                (
                    this.DestinationLink == input.DestinationLink ||
                    (this.DestinationLink != null &&
                    this.DestinationLink.Equals(input.DestinationLink))
                ) && 
                (
                    this.TicketSuggestionsResult == input.TicketSuggestionsResult ||
                    (this.TicketSuggestionsResult != null &&
                    this.TicketSuggestionsResult.Equals(input.TicketSuggestionsResult))
                ) && 
                (
                    this.TariffZones == input.TariffZones ||
                    this.TariffZones != null &&
                    input.TariffZones != null &&
                    this.TariffZones.SequenceEqual(input.TariffZones)
                ) && 
                (
                    this.Occupancy == input.Occupancy ||
                    (this.Occupancy != null &&
                    this.Occupancy.Equals(input.Occupancy))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DepartureAccessLink != null)
                {
                    hashCode = (hashCode * 59) + this.DepartureAccessLink.GetHashCode();
                }
                if (this.TripLegs != null)
                {
                    hashCode = (hashCode * 59) + this.TripLegs.GetHashCode();
                }
                if (this.ConnectionLinks != null)
                {
                    hashCode = (hashCode * 59) + this.ConnectionLinks.GetHashCode();
                }
                if (this.ArrivalAccessLink != null)
                {
                    hashCode = (hashCode * 59) + this.ArrivalAccessLink.GetHashCode();
                }
                if (this.DestinationLink != null)
                {
                    hashCode = (hashCode * 59) + this.DestinationLink.GetHashCode();
                }
                if (this.TicketSuggestionsResult != null)
                {
                    hashCode = (hashCode * 59) + this.TicketSuggestionsResult.GetHashCode();
                }
                if (this.TariffZones != null)
                {
                    hashCode = (hashCode * 59) + this.TariffZones.GetHashCode();
                }
                if (this.Occupancy != null)
                {
                    hashCode = (hashCode * 59) + this.Occupancy.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
