/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Represents the different types of transport modes.
    /// </summary>
    /// <value>Represents the different types of transport modes.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaWebV4ModelsTransportMode
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown,

        /// <summary>
        /// Enum None for value: none
        /// </summary>
        [EnumMember(Value = "none")]
        None,

        /// <summary>
        /// Enum Tram for value: tram
        /// </summary>
        [EnumMember(Value = "tram")]
        Tram,

        /// <summary>
        /// Enum Bus for value: bus
        /// </summary>
        [EnumMember(Value = "bus")]
        Bus,

        /// <summary>
        /// Enum Ferry for value: ferry
        /// </summary>
        [EnumMember(Value = "ferry")]
        Ferry,

        /// <summary>
        /// Enum Train for value: train
        /// </summary>
        [EnumMember(Value = "train")]
        Train,

        /// <summary>
        /// Enum Taxi for value: taxi
        /// </summary>
        [EnumMember(Value = "taxi")]
        Taxi,

        /// <summary>
        /// Enum Walk for value: walk
        /// </summary>
        [EnumMember(Value = "walk")]
        Walk,

        /// <summary>
        /// Enum Bike for value: bike
        /// </summary>
        [EnumMember(Value = "bike")]
        Bike,

        /// <summary>
        /// Enum Car for value: car
        /// </summary>
        [EnumMember(Value = "car")]
        Car,

        /// <summary>
        /// Enum Teletaxi for value: teletaxi
        /// </summary>
        [EnumMember(Value = "teletaxi")]
        Teletaxi
    }

}
