/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Pagination navigation links.
    /// </summary>
    [DataContract(Name = "VT.ApiPlaneraResa.Web.V4.Models.PaginationLinks")]
    public partial class VTApiPlaneraResaWebV4ModelsPaginationLinks : IEquatable<VTApiPlaneraResaWebV4ModelsPaginationLinks>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VTApiPlaneraResaWebV4ModelsPaginationLinks" /> class.
        /// </summary>
        /// <param name="previous">Link to the previous results page, if available, otherwise null..</param>
        /// <param name="next">Link to the next results page, if available, otherwise null. Not guaranteed to give a result if called..</param>
        /// <param name="current">Link to the current results page, if available, otherwise null. Not guaranteed to give a result if called..</param>
        public VTApiPlaneraResaWebV4ModelsPaginationLinks(string previous = default(string), string next = default(string), string current = default(string))
        {
            this.Previous = previous;
            this.Next = next;
            this.Current = current;
        }

        /// <summary>
        /// Link to the previous results page, if available, otherwise null.
        /// </summary>
        /// <value>Link to the previous results page, if available, otherwise null.</value>
        [DataMember(Name = "previous", EmitDefaultValue = true)]
        public string Previous { get; set; }

        /// <summary>
        /// Link to the next results page, if available, otherwise null. Not guaranteed to give a result if called.
        /// </summary>
        /// <value>Link to the next results page, if available, otherwise null. Not guaranteed to give a result if called.</value>
        [DataMember(Name = "next", EmitDefaultValue = true)]
        public string Next { get; set; }

        /// <summary>
        /// Link to the current results page, if available, otherwise null. Not guaranteed to give a result if called.
        /// </summary>
        /// <value>Link to the current results page, if available, otherwise null. Not guaranteed to give a result if called.</value>
        [DataMember(Name = "current", EmitDefaultValue = true)]
        public string Current { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VTApiPlaneraResaWebV4ModelsPaginationLinks {\n");
            sb.Append("  Previous: ").Append(Previous).Append("\n");
            sb.Append("  Next: ").Append(Next).Append("\n");
            sb.Append("  Current: ").Append(Current).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VTApiPlaneraResaWebV4ModelsPaginationLinks);
        }

        /// <summary>
        /// Returns true if VTApiPlaneraResaWebV4ModelsPaginationLinks instances are equal
        /// </summary>
        /// <param name="input">Instance of VTApiPlaneraResaWebV4ModelsPaginationLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VTApiPlaneraResaWebV4ModelsPaginationLinks input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Previous == input.Previous ||
                    (this.Previous != null &&
                    this.Previous.Equals(input.Previous))
                ) && 
                (
                    this.Next == input.Next ||
                    (this.Next != null &&
                    this.Next.Equals(input.Next))
                ) && 
                (
                    this.Current == input.Current ||
                    (this.Current != null &&
                    this.Current.Equals(input.Current))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Previous != null)
                {
                    hashCode = (hashCode * 59) + this.Previous.GetHashCode();
                }
                if (this.Next != null)
                {
                    hashCode = (hashCode * 59) + this.Next.GetHashCode();
                }
                if (this.Current != null)
                {
                    hashCode = (hashCode * 59) + this.Current.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
