/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Information about a line.
    /// </summary>
    [DataContract(Name = "VT.ApiPlaneraResa.Web.V4.Models.Positions.LineDetailsApiModel")]
    public partial class VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel : IEquatable<VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets TransportMode
        /// </summary>
        [DataMember(Name = "transportMode", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsTransportMode? TransportMode { get; set; }

        /// <summary>
        /// Gets or Sets TransportSubMode
        /// </summary>
        [DataMember(Name = "transportSubMode", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsTransportSubMode? TransportSubMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel" /> class.
        /// </summary>
        /// <param name="name">The line name..</param>
        /// <param name="backgroundColor">The background color of the line symbol..</param>
        /// <param name="foregroundColor">The foreground color of the line symbol..</param>
        /// <param name="borderColor">The border color of the line symbol..</param>
        /// <param name="transportMode">transportMode.</param>
        /// <param name="transportSubMode">transportSubMode.</param>
        public VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel(string name = default(string), string backgroundColor = default(string), string foregroundColor = default(string), string borderColor = default(string), VTApiPlaneraResaWebV4ModelsTransportMode? transportMode = default(VTApiPlaneraResaWebV4ModelsTransportMode?), VTApiPlaneraResaWebV4ModelsTransportSubMode? transportSubMode = default(VTApiPlaneraResaWebV4ModelsTransportSubMode?))
        {
            this.Name = name;
            this.BackgroundColor = backgroundColor;
            this.ForegroundColor = foregroundColor;
            this.BorderColor = borderColor;
            this.TransportMode = transportMode;
            this.TransportSubMode = transportSubMode;
        }

        /// <summary>
        /// The line name.
        /// </summary>
        /// <value>The line name.</value>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The background color of the line symbol.
        /// </summary>
        /// <value>The background color of the line symbol.</value>
        [DataMember(Name = "backgroundColor", EmitDefaultValue = true)]
        public string BackgroundColor { get; set; }

        /// <summary>
        /// The foreground color of the line symbol.
        /// </summary>
        /// <value>The foreground color of the line symbol.</value>
        [DataMember(Name = "foregroundColor", EmitDefaultValue = true)]
        public string ForegroundColor { get; set; }

        /// <summary>
        /// The border color of the line symbol.
        /// </summary>
        /// <value>The border color of the line symbol.</value>
        [DataMember(Name = "borderColor", EmitDefaultValue = true)]
        public string BorderColor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  BackgroundColor: ").Append(BackgroundColor).Append("\n");
            sb.Append("  ForegroundColor: ").Append(ForegroundColor).Append("\n");
            sb.Append("  BorderColor: ").Append(BorderColor).Append("\n");
            sb.Append("  TransportMode: ").Append(TransportMode).Append("\n");
            sb.Append("  TransportSubMode: ").Append(TransportSubMode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel);
        }

        /// <summary>
        /// Returns true if VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel instances are equal
        /// </summary>
        /// <param name="input">Instance of VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VTApiPlaneraResaWebV4ModelsPositionsLineDetailsApiModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.BackgroundColor == input.BackgroundColor ||
                    (this.BackgroundColor != null &&
                    this.BackgroundColor.Equals(input.BackgroundColor))
                ) && 
                (
                    this.ForegroundColor == input.ForegroundColor ||
                    (this.ForegroundColor != null &&
                    this.ForegroundColor.Equals(input.ForegroundColor))
                ) && 
                (
                    this.BorderColor == input.BorderColor ||
                    (this.BorderColor != null &&
                    this.BorderColor.Equals(input.BorderColor))
                ) && 
                (
                    this.TransportMode == input.TransportMode ||
                    this.TransportMode.Equals(input.TransportMode)
                ) && 
                (
                    this.TransportSubMode == input.TransportSubMode ||
                    this.TransportSubMode.Equals(input.TransportSubMode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.BackgroundColor != null)
                {
                    hashCode = (hashCode * 59) + this.BackgroundColor.GetHashCode();
                }
                if (this.ForegroundColor != null)
                {
                    hashCode = (hashCode * 59) + this.ForegroundColor.GetHashCode();
                }
                if (this.BorderColor != null)
                {
                    hashCode = (hashCode * 59) + this.BorderColor.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.TransportMode.GetHashCode();
                hashCode = (hashCode * 59) + this.TransportSubMode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
