/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Information about a service journey of a departure or arrival.
    /// </summary>
    [DataContract(Name = "VT.ApiPlaneraResa.Web.V4.Models.Journeys.ServiceJourneyApiModel")]
    public partial class VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel : IEquatable<VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel" /> class.
        /// </summary>
        /// <param name="gid">16-digit Västtrafik service journey gid. (required).</param>
        /// <param name="direction">A description of the direction..</param>
        /// <param name="directionDetails">directionDetails.</param>
        /// <param name="number">Västtrafik service journey number that the trip leg is a part of..</param>
        /// <param name="line">line.</param>
        public VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel(string gid = default(string), string direction = default(string), VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel directionDetails = default(VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel), string number = default(string), VTApiPlaneraResaWebV4ModelsJourneysLineApiModel line = default(VTApiPlaneraResaWebV4ModelsJourneysLineApiModel))
        {
            // to ensure "gid" is required (not null)
            if (gid == null)
            {
                throw new ArgumentNullException("gid is a required property for VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel and cannot be null");
            }
            this.Gid = gid;
            this.Direction = direction;
            this.DirectionDetails = directionDetails;
            this.Number = number;
            this.Line = line;
        }

        /// <summary>
        /// 16-digit Västtrafik service journey gid.
        /// </summary>
        /// <value>16-digit Västtrafik service journey gid.</value>
        [DataMember(Name = "gid", IsRequired = true, EmitDefaultValue = true)]
        public string Gid { get; set; }

        /// <summary>
        /// A description of the direction.
        /// </summary>
        /// <value>A description of the direction.</value>
        [DataMember(Name = "direction", EmitDefaultValue = true)]
        public string Direction { get; set; }

        /// <summary>
        /// Gets or Sets DirectionDetails
        /// </summary>
        [DataMember(Name = "directionDetails", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsDirectionDetailsApiModel DirectionDetails { get; set; }

        /// <summary>
        /// Västtrafik service journey number that the trip leg is a part of.
        /// </summary>
        /// <value>Västtrafik service journey number that the trip leg is a part of.</value>
        [DataMember(Name = "number", EmitDefaultValue = true)]
        public string Number { get; set; }

        /// <summary>
        /// Gets or Sets Line
        /// </summary>
        [DataMember(Name = "line", EmitDefaultValue = false)]
        public VTApiPlaneraResaWebV4ModelsJourneysLineApiModel Line { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel {\n");
            sb.Append("  Gid: ").Append(Gid).Append("\n");
            sb.Append("  Direction: ").Append(Direction).Append("\n");
            sb.Append("  DirectionDetails: ").Append(DirectionDetails).Append("\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  Line: ").Append(Line).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel);
        }

        /// <summary>
        /// Returns true if VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel instances are equal
        /// </summary>
        /// <param name="input">Instance of VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VTApiPlaneraResaWebV4ModelsJourneysServiceJourneyApiModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Gid == input.Gid ||
                    (this.Gid != null &&
                    this.Gid.Equals(input.Gid))
                ) && 
                (
                    this.Direction == input.Direction ||
                    (this.Direction != null &&
                    this.Direction.Equals(input.Direction))
                ) && 
                (
                    this.DirectionDetails == input.DirectionDetails ||
                    (this.DirectionDetails != null &&
                    this.DirectionDetails.Equals(input.DirectionDetails))
                ) && 
                (
                    this.Number == input.Number ||
                    (this.Number != null &&
                    this.Number.Equals(input.Number))
                ) && 
                (
                    this.Line == input.Line ||
                    (this.Line != null &&
                    this.Line.Equals(input.Line))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Gid != null)
                {
                    hashCode = (hashCode * 59) + this.Gid.GetHashCode();
                }
                if (this.Direction != null)
                {
                    hashCode = (hashCode * 59) + this.Direction.GetHashCode();
                }
                if (this.DirectionDetails != null)
                {
                    hashCode = (hashCode * 59) + this.DirectionDetails.GetHashCode();
                }
                if (this.Number != null)
                {
                    hashCode = (hashCode * 59) + this.Number.GetHashCode();
                }
                if (this.Line != null)
                {
                    hashCode = (hashCode * 59) + this.Line.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Gid (string) minLength
            if (this.Gid != null && this.Gid.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Gid, length must be greater than 1.", new [] { "Gid" });
            }

            yield break;
        }
    }

}
